Improve and add some shell scripts to manipulate the stack

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -1,9 +1,15 @@
 #!/bin/sh
 
+aws cloudformation delete-stack --stack-name development-environment
+if [ "$?" != 255 ]; then
+    echo "Waiting for stack to be deleted.."
+    aws cloudformation wait stack-delete-complete --stack-name development-environment
+fi
+echo "Delete complete."
+aws s3 mb s3://development-environment-template
+
 aws cloudformation validate-template \
     --template-body file://./template.yml
-
-npx cfn-lint validate ./template.yml
 
 # Remake a ssh key for the bastion server
 chmod 775 ./bastion-of-development-environment.pem
@@ -25,14 +31,20 @@ aws cloudformation package \
     --s3-bucket development-environment-template \
     --output-template-file packaged-template.yml
 
+npx cfn-lint validate ./packaged-template.yml
+
+if [ "$?" = 255 ]; then exit 1; fi
+
 # need this capabilities to create a stack
 aws cloudformation deploy \
     --stack-name development-environment \
     --template-file ./packaged-template.yml \
-    --capabilities CAPABILITY_IAM \
+    --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM \
     --tags date="$(date '+%Y%m%d%H%M%S')"
 
+# If some error occurs, describe what has happend and delete the failed stack.
 if [ "$?" = 255 ]; then
-    aws cloudformation describe-stack-events --stack-name development-environment | jq '.StackEvents[] | select(.ResourceStatus == "CREATE_FAILED") | { id: .LogicalResourceId, type: .ResourceType, reason: .ResourceStatusReason }'
+    aws cloudformation describe-stack-events --stack-name development-environment | \
+        jq '.StackEvents[] | select(.ResourceStatus == "CREATE_FAILED") | { id: .LogicalResourceId, type: .ResourceType, reason: .ResourceStatusReason }'
     aws cloudformation delete-stack --stack-name development-environment
 fi
